language: ruby

addons:
  apt:
    packages:
      - make
      - fonts-lmodern
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-latex-extra
      - texlive-math-extra
      - texlive-science
      - texlive-xetex
      - texlive-latex-base
      - latex-xcolor

script:
  - make
  - mkdir -p pdf
  - mv cv.pdf pdf/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
